[tool.black]
exclude = '^/(\.|dist|pybuild|venv)'

[tool.coverage.run]
omit = ["*/tests/*", "cumulusci/files/*", ]
source = ["cumulusci", ]

[tool.coverage.report]
exclude_lines = ["pragma: no cover", "@abstract", ]
