version: 2.1

defaults: &defaults
  docker:
    - image: circleci/python:3.7-browsers
  environment:
    - BROWSER: headlesschrome
  working_directory: ~/repo

jobs:
  test_release:
    <<: *defaults
    environment:
      CUMULUSCI_KEYCHAIN_CLASS: cumulusci.core.keychain.EnvironmentProjectKeychain
    steps:
      - checkout
      - run:
          name: Skip unless master or PR build
          command: |
            if [ "$CIRCLE_BRANCH" != "master" ] && [ -z "$CIRCLE_PULL_REQUEST" ]; then
              circleci step halt
            fi
      - run:
          name: Install Python dependencies
          command: |
            virtualenv venv
            venv/bin/pip install -r requirements_dev.txt
      - run:
          name: Check out CumulusCI-Test
          command: |
            git clone https://github.com/SFDO-Tooling/CumulusCI-Test
      - run:
          name: Install sfdx
          command: |
            mkdir sfdx
            wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJ -C sfdx --strip-components 1
            ./sfdx/install
            cd CumulusCI-Test
            echo $SFDX_HUB_KEY_BASE64 | base64 --decode > sfdx.key
            echo 'export SFDX_HUB_KEY="$(echo $SFDX_HUB_KEY_BASE64 | base64 --decode)"' >> $BASH_ENV
            sfdx force:auth:jwt:grant --clientid $SFDX_CLIENT_ID --jwtkeyfile sfdx.key --username $SFDX_HUB_USERNAME --setdefaultdevhubusername -a hub
      - run:
          name: Run ci_feature flow
          command: |
            cd CumulusCI-Test
            ../venv/bin/coverage run --append --rcfile=../.coveragerc --source=../cumulusci ../venv/bin/cci flow run ci_feature --org scratch --delete-org
      - run:
          name: Run ci_beta flow
          command: |
            cd CumulusCI-Test
            ../venv/bin/coverage run --append --rcfile=../.coveragerc --source=../cumulusci ../venv/bin/cci flow run ci_beta --org scratch --delete-org
      - run:
          name: Run ci_master flow
          command: |
            cd CumulusCI-Test
            ../venv/bin/coverage run --append --rcfile=../.coveragerc --source=../cumulusci ../venv/bin/cci flow run ci_master --org scratch --delete-org
      - run:
          name: Run release_beta flow
          command: |
            cd CumulusCI-Test
            ../venv/bin/coverage run --append --rcfile=../.coveragerc --source=../cumulusci ../venv/bin/cci flow run release_beta --org packaging
      - run:
          name: Preserve coverage
          command: |
            mv CumulusCI-Test/.coverage .coverage.release
      - persist_to_workspace:
          root: .
          paths:
            - .coverage.release

workflows:
  version: 2
  build_test_report:
    jobs:
      - test_release:
          filters:
            branches:
              ignore:
                - /dependabot\/.*/
