name: Publish Python distributions to TestPyPI

on:
  push:
    branches:
    - feature/release-action

jobs:
  build-n-publish:
    name: Build and publish Python distributions to TestPyPI
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Build source tarball and binary wheel
        run: python setup.py sdist bdist_wheel
      - name: Install twine
        run: python -m pip install twine
      - name: Upload to TestPyPI
        run: twine upload dist/*
        env:
          TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
